#!/usr/bin/env python3
"""Verify that a generated report's DAX queries produce the numbers it shows.

Every report generated by the prompts in this repo carries the DAX query that
produced each section's numbers, in one of three markup families:
powerbireport.md wraps them in collapsible ``dax-toggle`` blocks, the QBR
template uses ``<details class="dax-proof">`` panels, and projectreport.md uses
``<div class="dax-query">`` panels. This tool makes that checkability claim
testable end to end:

1. Extract every DAX query from the report HTML (all three markup families).
   A single panel that bundles several ``EVALUATE`` blocks (as the QBR does) is
   split into one query per statement, since executeQueries returns one result
   set per query.
2. Re-run each query against your Power BI tenant, through the same alias
   reverse-mapping the MCP server uses (``server.anonymizer``), so queries
   that still contain aliases like Client_A or <PERSON_1> execute correctly.
3. Compare the returned values against the numbers the report states in its
   ``-- Result:`` comment lines. Numbers a report computes from the query's
   output rather than reading directly (a percentage, a column total, a
   complement) are reported as "derived, not directly queryable" instead of
   failing. A query with no ``-- Result:`` line is run execute-only: it must
   run without error, but no value is checked.
4. Print a per-query PASS/FAIL table and exit nonzero on any FAIL or ERROR.

Usage:
    python3 tools/verify_report.py report.html
    python3 tools/verify_report.py report.html --dataset-id <uuid>
    python3 tools/verify_report.py report.html --extract-only
    python3 tools/verify_report.py report.html --json results.json

The dataset id is resolved the same way the MCP server resolves it:
--dataset-id flag, then POWERBI_MCP_DATASET_ID / POWERBI_MCP_CONFIG env vars,
then server/config.json, then ~/.powerbi-mcp/config.json.

Expected values come from comment lines inside each query block, written by
the report prompts, for example:

    EVALUATE ROW("total_tickets", COUNTROWS('BI_Autotask_Tickets'))
    -- Result: total_tickets = 1284

A query without a ``-- Result:`` line is still executed and must run without
error, but its values cannot be checked; the table marks it "PASS (ran, no
expected values)". Numbers may carry a currency symbol, thousands separators,
decimals, or a percent sign; a value shown as a percentage matches both the
percent form (93) and the fraction form (0.93), rounded to the precision the
report displays.

This script only needs the Python standard library for extraction and
comparison. Execution additionally needs the ``requests`` package and the
``server/`` package from this repo (for authentication and alias rewriting).
"""

import argparse
import json
import os
import re
import sys
from html.parser import HTMLParser
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Matches the result comment convention used by the report prompts.
# English "Result" and Dutch "Resultaat" are both produced in the wild.
_RESULT_COMMENT = re.compile(r"^\s*--\s*(?:Result|Resultaat)\s*:\s*(?P<body>.*)$", re.I)

# A number as reports render it: optional sign, optional currency symbol,
# digits with optional thousands separators and decimal part, optional %.
# The leading (?<![A-Za-z0-9]) refuses digits glued to a letter or digit, so
# "M365", "Q2" and "P4" are not read as 365, 2 and 4 (and the digit right after
# the rejected letter does not start a fresh "65" match either).
_NUMBER_TOKEN = re.compile(r"(?<![A-Za-z0-9])[-+]?(?:[€$£]\s?)?\d(?:[\d.,]*\d)?\s?%?")

# Product names with a numeric part ("Microsoft 365", "Office 365"): the number
# is branding, not a metric. Stripped before extraction like the calendar labels.
_PRODUCT_NAME = re.compile(
    r"\b(?:Microsoft|Office|Windows|Dynamics|SharePoint|SQL\s+Server)\s+\d+\b", re.I)

# Month names (EN + NL, full and 3-letter) used to recognise date expressions.
_MONTHS = (
    r"jan(?:uari|uary)?|feb(?:ruari|ruary)?|maart|mar(?:ch)?|apr(?:il)?|mei|may"
    r"|jun[ie]?|june|jul[iy]?|july|aug(?:ustus|ust)?|sep(?:tember)?|okt(?:ober)?"
    r"|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?"
)

# Date expressions whose digits are calendar labels, never queryable metrics:
# "21 Jan 2026", "Jan 2026", "2026-01-21". Stripped before number extraction so
# a report's time labels do not turn into expected values that then "fail".
_DATE_EXPR = re.compile(
    rf"\b\d{{1,2}}\s+(?:{_MONTHS})\.?\s+\d{{2,4}}\b"       # 21 Jan 2026
    rf"|\b(?:{_MONTHS})\.?\s+\d{{4}}\b"                    # Jan 2026
    rf"|\b\d{{4}}-\d{{2}}-\d{{2}}\b",                      # 2026-01-21
    re.I,
)

# A bare four-digit year (1900-2099). Report prose uses these as time labels
# ("Q2 2026", "in 2025"), not as metrics; dropping them is the safe direction
# (fewer value checks, never a false failure on a calendar year).
_YEAR_TOKEN = re.compile(r"\b(?:19|20)\d{2}\b")


def _strip_calendar_tokens(text):
    """Remove date expressions, bare years, and numeric product names so number
    extraction sees only values, not calendar labels or branding."""
    text = _PRODUCT_NAME.sub(" ", text)
    return _YEAR_TOKEN.sub(" ", _DATE_EXPR.sub(" ", text))


# ---------------------------------------------------------------------------
# Extraction
# ---------------------------------------------------------------------------

class _PanelExtractor(HTMLParser):
    """Pulls DAX out of the three report families: dax-toggle blocks
    (powerbireport), dax-proof details (QBR), and dax-query panels
    (projectreport). HTMLParser unescapes entities, so &lt;PERSON_1&gt; in the
    source arrives here as <PERSON_1>, ready to execute."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.panels = []
        self._section_label = ""
        self._heading = ""
        self._in_heading = False
        # dax-proof state
        self._in_proof = False
        # dax-toggle state
        self._toggle_depth = 0
        self._in_trigger_span = False
        self._trigger_text = ""
        # dax-query state (projectreport)
        self._query_depth = 0
        self._in_title_span = False
        self._title_text = ""
        # shared pre capture
        self._in_pre = False
        self._pre_text = ""
        self._pre_family = ""

    @staticmethod
    def _classes(attrs):
        return dict(attrs).get("class", "").split()

    def handle_starttag(self, tag, attrs):
        attrs_dict = dict(attrs)
        classes = self._classes(attrs)
        if tag == "section" and attrs_dict.get("data-screen-label"):
            self._section_label = attrs_dict["data-screen-label"]
        elif tag in ("h1", "h2", "h3"):
            self._in_heading = True
            self._heading = ""
        elif tag == "details" and "dax-proof" in classes:
            self._in_proof = True
        elif tag == "div":
            if "dax-toggle" in classes:
                self._toggle_depth = 1
                self._trigger_text = ""
            elif "dax-query" in classes:
                self._query_depth = 1
                self._title_text = ""
            elif self._toggle_depth:
                self._toggle_depth += 1
            elif self._query_depth:
                self._query_depth += 1
        elif tag == "span":
            if self._toggle_depth:
                self._in_trigger_span = True
            elif self._query_depth and "dax-title" in classes:
                self._in_title_span = True
        elif tag == "pre" and (self._in_proof or self._toggle_depth
                               or self._query_depth):
            self._in_pre = True
            self._pre_text = ""
            self._pre_family = ("dax-proof" if self._in_proof
                                else "dax-toggle" if self._toggle_depth
                                else "dax-query")

    def handle_endtag(self, tag):
        if tag == "pre" and self._in_pre:
            self._in_pre = False
            self._finish_panel()
        elif tag == "details" and self._in_proof:
            self._in_proof = False
        elif tag == "div" and self._toggle_depth:
            self._toggle_depth -= 1
        elif tag == "div" and self._query_depth:
            self._query_depth -= 1
        elif tag == "span":
            self._in_trigger_span = False
            self._in_title_span = False
        elif tag in ("h1", "h2", "h3"):
            self._in_heading = False

    def handle_data(self, data):
        if self._in_pre:
            self._pre_text += data
        elif self._in_heading:
            self._heading += data
        elif self._in_trigger_span:
            self._trigger_text += data
        elif self._in_title_span:
            self._title_text += data

    def _finish_panel(self):
        text = self._pre_text.strip()
        if not text:
            return
        if self._pre_family == "dax-toggle":
            base = re.sub(r"^\s*View DAX Query\s*[—–-]?\s*", "", self._trigger_text).strip()
            base = base or self._heading.strip() or "dax-toggle"
        elif self._pre_family == "dax-query":
            base = self._title_text.strip() or self._heading.strip() or "dax-query"
        else:
            base = self._section_label or self._heading.strip() or "dax-proof"

        statements = split_dax_statements(text)
        for idx, statement in enumerate(statements, 1):
            query_lines, expected = [], []
            for line in statement.split("\n"):
                m = _RESULT_COMMENT.match(line)
                if m:
                    expected.extend(parse_numbers(m.group("body")))
                else:
                    query_lines.append(line)
            query = "\n".join(query_lines).strip()
            if not query:
                continue
            label = base if len(statements) == 1 else f"{base} ({idx}/{len(statements)})"
            self.panels.append({
                "section": label,
                "family": self._pre_family,
                "query": query,
                "expected": expected,
            })


_STATEMENT_KEYWORD = re.compile(r"^\s*(DEFINE|EVALUATE)\b", re.I)


def split_dax_statements(text):
    """Split a panel body into individual DAX statements.

    QBR proof panels bundle several ``EVALUATE`` blocks (optionally each with a
    leading ``DEFINE``) in one ``<pre>``; the executeQueries endpoint returns a
    single result set per query, so each statement must run on its own. A
    ``DEFINE`` always opens a new statement; an ``EVALUATE`` opens one unless it
    is the body of the ``DEFINE`` just seen. Comment and ``-- Result:`` lines
    ride along with the statement they follow.

    Returns a list of statement strings. A body with one (or no) statement is
    returned unchanged as a single element.
    """
    lines = text.split("\n")
    starts = []
    define_open = False
    for i, line in enumerate(lines):
        m = _STATEMENT_KEYWORD.match(line)
        if not m:
            continue
        if m.group(1).upper() == "DEFINE":
            starts.append(i)
            define_open = True
        else:  # EVALUATE
            if define_open:
                define_open = False  # closes the DEFINE ... EVALUATE statement
            else:
                starts.append(i)
    if len(starts) <= 1:
        return [text]
    # Keep any leading comments with the first statement; every later statement
    # begins at its own keyword line.
    bounds = [0] + starts[1:] + [len(lines)]
    return ["\n".join(lines[a:b]) for a, b in zip(bounds, bounds[1:])]


def extract_panels(html_text):
    """Return a list of panels: {section, family, query, expected}."""
    parser = _PanelExtractor()
    parser.feed(html_text)
    return parser.panels


# ---------------------------------------------------------------------------
# Number parsing and comparison
# ---------------------------------------------------------------------------

def _normalize_token(token):
    """Turn one rendered number token into (value, decimals, is_percent)."""
    is_percent = token.rstrip().endswith("%")
    cleaned = re.sub(r"[€$£%\s]", "", token)
    sign = 1
    if cleaned.startswith(("-", "+")):
        sign = -1 if cleaned[0] == "-" else 1
        cleaned = cleaned[1:]
    if "." in cleaned and "," in cleaned:
        # The last separator is the decimal point, the other marks thousands.
        if cleaned.rfind(",") > cleaned.rfind("."):
            cleaned = cleaned.replace(".", "").replace(",", ".")
        else:
            cleaned = cleaned.replace(",", "")
    elif "," in cleaned:
        parts = cleaned.split(",")
        if len(parts) > 2 or (len(parts) == 2 and len(parts[1]) == 3):
            cleaned = cleaned.replace(",", "")  # thousands: 1,284 or 1,234,567
        else:
            cleaned = cleaned.replace(",", ".")  # decimal comma: 4,7
    elif cleaned.count(".") > 1:
        cleaned = cleaned.replace(".", "")  # thousands: 1.234.567
    decimals = len(cleaned.split(".")[1]) if "." in cleaned else 0
    return (sign * float(cleaned), decimals, is_percent)


def parse_numbers(text):
    """Extract every number from a piece of report text.

    Digits embedded in words ("Microsoft 365") and calendar labels (years,
    "21 Jan 2026") are not numbers a query returns, so they are left out.

    Returns a list of (value, decimals, is_percent) tuples.
    """
    out = []
    text = _strip_calendar_tokens(text)
    for m in _NUMBER_TOKEN.finditer(text):
        token = m.group(0)
        if not re.search(r"\d", token):
            continue
        try:
            out.append(_normalize_token(token))
        except ValueError:
            continue
    return out


def collect_returned_values(response_json):
    """Flatten every numeric value out of an executeQueries response."""
    values = []

    def walk(node):
        if isinstance(node, bool):
            return
        if node is None:
            # includeNulls returns BLANK() cells as null; reports render those
            # as 0 ("0 (null)"), so an expected 0 must match a null cell.
            values.append(0.0)
        elif isinstance(node, (int, float)):
            values.append(float(node))
        elif isinstance(node, str):
            try:
                values.append(float(node))
            except ValueError:
                pass
        elif isinstance(node, dict):
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    for result in response_json.get("results", []):
        for table in result.get("tables", []):
            walk(table.get("rows", []))
    return values


def _cell_float(v):
    """One result cell as a float, or None if it is not numeric. null -> 0."""
    if isinstance(v, bool):
        return None
    if v is None:
        return 0.0
    if isinstance(v, (int, float)):
        return float(v)
    if isinstance(v, str):
        try:
            return float(v)
        except ValueError:
            return None
    return None


def collect_derived_values(response_json):
    """Values a report legitimately derives from a query's output rather than
    reading directly: a column total (SUM over the rows of one column) and the
    difference between two column totals (a complement, e.g. unmanaged = total -
    managed). Used to classify an unmatched number as "derived" instead of a
    failure, alongside percentages."""
    col_sums = []
    for result in response_json.get("results", []):
        for table in result.get("tables", []):
            columns = {}
            for row in table.get("rows", []):
                if not isinstance(row, dict):
                    continue
                for key, value in row.items():
                    fv = _cell_float(value)
                    if fv is not None:
                        columns.setdefault(key, []).append(fv)
            col_sums.extend(sum(vals) for vals in columns.values())
    derived = set(col_sums)
    for i in range(len(col_sums)):
        for j in range(i + 1, len(col_sums)):
            derived.add(abs(col_sums[i] - col_sums[j]))
    return sorted(derived)


def _matches(expected, returned_values):
    value, decimals, is_percent = expected
    tolerance = 10 ** -(decimals + 6)
    for rv in returned_values:
        if abs(round(rv, decimals) - value) < tolerance:
            return True
        # A report shows "93%" whether the model returned 93 or 0.93.
        if is_percent and abs(round(rv * 100, decimals) - value) < tolerance:
            return True
    return False


def diff_expected(expected, returned_values):
    """Return the subset of expected numbers not found in the returned values."""
    return [e for e in expected if not _matches(e, returned_values)]


def format_expected(expected):
    value, decimals, is_percent = expected
    rendered = f"{value:.{decimals}f}"
    return rendered + "%" if is_percent else rendered


# ---------------------------------------------------------------------------
# Execution against the tenant
# ---------------------------------------------------------------------------

def resolve_dataset_id(cli_value=None):
    """Resolve the dataset id the same way the MCP server does."""
    if cli_value:
        return cli_value
    env_dataset = os.environ.get("POWERBI_MCP_DATASET_ID")
    if env_dataset:
        return env_dataset
    env_config = os.environ.get("POWERBI_MCP_CONFIG")
    if env_config:
        try:
            dataset = json.loads(env_config).get("default_dataset_id")
            if dataset:
                return dataset
        except json.JSONDecodeError:
            pass
    for path in (REPO_ROOT / "server" / "config.json",
                 Path.home() / ".powerbi-mcp" / "config.json"):
        if path.exists():
            try:
                with open(path) as f:
                    dataset = json.load(f).get("default_dataset_id")
                if dataset:
                    return dataset
            except Exception:
                continue
    return None


def load_alias_mapping(mapping_path=None):
    """Load the alias -> real value mapping saved by the MCP server, if any."""
    path = mapping_path or (Path.home() / ".powerbi-mcp" / "sessions" / "latest" / "mapping.json")
    path = Path(path)
    if not path.exists():
        return {}
    try:
        with open(path) as f:
            return json.load(f).get("mappings", {})
    except Exception:
        return {}


def make_live_executor(dataset_id):
    """Build an executor that runs DAX against the real tenant, reusing the
    MCP server's auth. Imports are local so extraction and comparison stay
    dependency-free."""
    sys.path.insert(0, str(REPO_ROOT))
    import requests
    from server.auth import get_powerbi_headers

    def run(query):
        response = requests.post(
            f"https://api.powerbi.com/v1.0/myorg/datasets/{dataset_id}/executeQueries",
            headers=get_powerbi_headers(),
            json={"queries": [{"query": query}],
                  "serializerSettings": {"includeNulls": True}},
        )
        response.raise_for_status()
        payload = response.json()
        error = payload.get("results", [{}])[0].get("error")
        if error:
            raise RuntimeError(error.get("message", str(error)))
        return payload

    return run


def rewrite_aliases(query, mapping):
    """Rewrite alias literals (Client_A, <PERSON_1>, ...) back to real values
    using the same code path the MCP server's execute_dax uses."""
    if not mapping:
        return query, 0
    sys.path.insert(0, str(REPO_ROOT))
    from server.anonymizer import rewrite_alias_literals
    return rewrite_alias_literals(query, mapping)


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------

def verify_panels(panels, executor, mapping=None):
    """Run every panel's query and diff the values. Returns result dicts."""
    results = []
    for panel in panels:
        query, rewritten = rewrite_aliases(panel["query"], mapping or {})
        entry = {
            "section": panel["section"],
            "family": panel["family"],
            "aliases_rewritten": rewritten,
            "expected": [format_expected(e) for e in panel["expected"]],
        }
        try:
            response = executor(query)
        except Exception as exc:
            entry.update(status="ERROR", detail=str(exc))
            results.append(entry)
            continue
        returned = collect_returned_values(response)
        if not panel["expected"]:
            entry.update(status="PASS", detail="ran, no expected values",
                         value_checked=False)
        else:
            missing = diff_expected(panel["expected"], returned)
            # A value the report computes from the query's output rather than
            # reading directly is not a failure: a percentage (166/218 = 76%),
            # a column total, or a complement (unmanaged = total - managed).
            # Only a plain number the query should have returned but did not is
            # a real mismatch.
            derived_pool = collect_derived_values(response)
            derived = [e for e in missing if e[2] or _matches(e, derived_pool)]
            hard_missing = [e for e in missing if e not in derived]
            checked = len(panel["expected"]) - len(missing)
            if hard_missing:
                entry.update(
                    status="FAIL",
                    detail="expected {} not in returned values {}".format(
                        ", ".join(format_expected(e) for e in hard_missing),
                        [round(v, 4) for v in returned[:12]],
                    ),
                    value_checked=True,
                    derived=[format_expected(e) for e in derived],
                )
            else:
                detail = f"{checked} value(s) match"
                if derived:
                    detail += (f"; {len(derived)} derived, not directly "
                               f"queryable ({', '.join(format_expected(e) for e in derived)})")
                entry.update(status="PASS", detail=detail,
                             value_checked=checked > 0,
                             derived=[format_expected(e) for e in derived])
        results.append(entry)
    return results


def print_table(results):
    width = max([len(r["section"]) for r in results] + [7])
    print(f"{'SECTION':<{width}}  {'STATUS':<6}  DETAIL")
    print(f"{'-' * width}  {'-' * 6}  {'-' * 40}")
    for r in results:
        note = f" [{r['aliases_rewritten']} alias(es) rewritten]" if r["aliases_rewritten"] else ""
        print(f"{r['section']:<{width}}  {r['status']:<6}  {r['detail']}{note}")


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Re-run every DAX query in a generated report and check "
                    "the returned values against the numbers the report shows.")
    parser.add_argument("report", type=Path, help="Report HTML file")
    parser.add_argument("--dataset-id", help="Dataset to run the queries against "
                        "(default: same resolution as the MCP server)")
    parser.add_argument("--mapping", type=Path, default=None,
                        help="Path to a mapping.json for alias rewriting "
                             "(default: ~/.powerbi-mcp/sessions/latest/mapping.json)")
    parser.add_argument("--extract-only", action="store_true",
                        help="Only extract and list the queries, do not execute")
    parser.add_argument("--json", type=Path, default=None,
                        help="Also write the results as JSON to this path")
    args = parser.parse_args(argv)

    if not args.report.exists():
        print(f"Error: report not found: {args.report}", file=sys.stderr)
        return 2

    panels = extract_panels(args.report.read_text(encoding="utf-8"))
    if not panels:
        print("No DAX queries found. Expected dax-toggle blocks "
              "(powerbireport), dax-proof details (QBR), or dax-query panels "
              "(projectreport) in the report.", file=sys.stderr)
        return 2

    print(f"Extracted {len(panels)} DAX quer{'y' if len(panels) == 1 else 'ies'} "
          f"({sum(1 for p in panels if p['family'] == 'dax-toggle')} dax-toggle, "
          f"{sum(1 for p in panels if p['family'] == 'dax-proof')} dax-proof, "
          f"{sum(1 for p in panels if p['family'] == 'dax-query')} dax-query)")

    if args.extract_only:
        for i, p in enumerate(panels, 1):
            expected = ", ".join(format_expected(e) for e in p["expected"]) or "none"
            print(f"\n[{i}] {p['section']} ({p['family']}, expected: {expected})")
            print(p["query"])
        return 0

    dataset_id = resolve_dataset_id(args.dataset_id)
    if not dataset_id:
        print("Error: no dataset id. Pass --dataset-id or set "
              "default_dataset_id in config.json.", file=sys.stderr)
        return 2

    mapping = load_alias_mapping(args.mapping)
    executor = make_live_executor(dataset_id)
    results = verify_panels(panels, executor, mapping)

    print()
    print_table(results)

    passed = sum(1 for r in results if r["status"] == "PASS")
    checked = sum(1 for r in results if r.get("value_checked"))
    exec_only = sum(1 for r in results
                    if r["status"] == "PASS" and not r.get("value_checked"))
    failed = [r for r in results if r["status"] in ("FAIL", "ERROR")]
    print(f"\n{passed}/{len(results)} passed "
          f"({checked} value-checked against the report's stated numbers, "
          f"{exec_only} ran execute-only)")

    if args.json:
        args.json.write_text(json.dumps(
            {"report": str(args.report), "dataset_id": dataset_id,
             "total": len(results), "passed": passed, "failed": len(failed),
             "results": results}, indent=2))
        print(f"JSON written to {args.json}")

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
